//go:build ignore
// +build ignore

// Run this from your project root:
//   go run gen_constants/main.go
//
// Generates two files inside watermark/ package:
//   watermark/constants_data.go        — pre-computed 16x16 matrices + CalculateChangeMatrix method
//   watermark/performwatermark_gen.go  — generic PerformEmbed / PerformExtract

package main

import (
	"fmt"
	"math"
	"os"
	"strings"
)

// N is the block size. Change this value to switch between block sizes.
// 8  → 8x8  DCT  (denominator = 2*8  = 16,  Uk/Vk use sqrt(1/8)  or sqrt(2/8))
// 16 → 16x16 DCT (denominator = 2*16 = 32,  Uk/Vk use sqrt(1/16) or sqrt(2/16))
const N = 8

// Local copy of Constants struct — only used inside this generator.
// Const_matrix is now [N][N] but since Go requires compile-time array sizes,
// we store it as a flat slice in the generator and emit it as a 2D slice in the output.
type Constants struct {
	U            int
	V            int
	Const_matrix [][]float64 // [N][N]
	Uk           float64
	Vk           float64
	Nc           float64
}

// createConstant computes all values for one (u,v) frequency pair.
//
// DCT-II basis function for an N×N block:
//
//	B_uv(x,y) = Uk * Vk * cos(pi*(2x+1)*u / (2N)) * cos(pi*(2y+1)*v / (2N))
//
// Normalization coefficients:
//
//	Uk = sqrt(1/N) if u==0, else sqrt(2/N)
//	Vk = sqrt(1/N) if v==0, else sqrt(2/N)
//
// Nc = Uk * Vk  (pre-multiplied scalar, avoids repeating the multiply at runtime)
//
// Const_matrix[i][j] stores the cosine product WITHOUT Nc, so that:
//
//	FindValueOptimized = Nc * sum(block[x][y] * Const_matrix[y][x])
func createConstant(u, v int) *Constants {
	d := &Constants{U: u, V: v}

	// Normalization coefficients for N×N DCT
	if u == 0 {
		d.Uk = math.Sqrt(1.0 / float64(N))
	} else {
		d.Uk = math.Sqrt(2.0 / float64(N))
	}
	if v == 0 {
		d.Vk = math.Sqrt(1.0 / float64(N))
	} else {
		d.Vk = math.Sqrt(2.0 / float64(N))
	}
	d.Nc = d.Uk * d.Vk

	// Cosine basis matrix — denominator is 2*N
	denom := 2.0 * float64(N)
	d.Const_matrix = make([][]float64, N)
	for i := 0; i < N; i++ {
		d.Const_matrix[i] = make([]float64, N)
		for j := 0; j < N; j++ {
			d.Const_matrix[i][j] =
				math.Cos((math.Pi*float64(2*j+1)*float64(u))/denom) *
					math.Cos((math.Pi*float64(2*i+1)*float64(v))/denom)
		}
	}
	return d
}

// ── ADD / REMOVE PAIRS HERE ────────────────────────────────────────────────
// Re-run `go run gen_constants/main.go` after any change.
var pairs = [][2]int{
	{2, 3}, // pair 1
	{3, 2}, // pair 2
	//{7, 8}, // pair 3
	//{8, 7}, // pair 4
}

func main() {
	fmt.Printf("Generating for %dx%d blocks (%d pairs)...\n", N, N, len(pairs))
	writeConstantsData()
	writePerformWatermarkGen()
}

// ── FILE 1: watermark/constants_data.go ───────────────────────────────────
func writeConstantsData() {
	var sb strings.Builder

	sb.WriteString("// Code generated by gen_constants/main.go — DO NOT EDIT.\n")
	sb.WriteString(fmt.Sprintf("// Block size: %dx%d DCT\n\n", N, N))
	sb.WriteString("package engine\n\n")
	sb.WriteString("import \"math\"\n\n")

	// ── Constants struct (sized for N×N) ──
	sb.WriteString("// BlockSize is the DCT block dimension this file was generated for.\n")
	sb.WriteString(fmt.Sprintf("const BlockSize = %d\n\n", N))

	sb.WriteString("// Constants holds the pre-computed basis values for one (u,v) DCT frequency.\n")
	sb.WriteString("type Constants struct {\n")
	sb.WriteString("\tU, V         int\n")
	sb.WriteString("\tUk, Vk, Nc  float64\n")
	sb.WriteString(fmt.Sprintf("\tConst_matrix [%d][%d]float64\n", N, N))
	sb.WriteString("}\n\n")

	// ── FindValueOptimized method ──
	sb.WriteString("// FindValueOptimized computes the (u,v) DCT coefficient of block via dot product.\n")
	sb.WriteString("// Complexity: O(N²) — no full DCT needed.\n")
	sb.WriteString("func (d *Constants) FindValueOptimized(block [][]float64) float64 {\n")
	sb.WriteString("\ttotal := 0.0\n")
	sb.WriteString(fmt.Sprintf("\tfor y := 0; y < %d; y++ {\n", N))
	sb.WriteString(fmt.Sprintf("\t\tfor x := 0; x < %d; x++ {\n", N))
	sb.WriteString("\t\t\ttotal += block[x][y] * d.Const_matrix[y][x]\n")
	sb.WriteString("\t\t}\n")
	sb.WriteString("\t}\n")
	sb.WriteString("\treturn d.Nc * total\n")
	sb.WriteString("}\n\n")

	// ── precomputedConstants map ──
	sb.WriteString("// precomputedConstants maps (u*100+v) -> *Constants for O(1) retrieval.\n")
	sb.WriteString("var precomputedConstants = map[int]*Constants{\n")
	for _, p := range pairs {
		u, v := p[0], p[1]
		c := createConstant(u, v)
		key := u*100 + v

		sb.WriteString(fmt.Sprintf("\t// (u=%d, v=%d)\n", u, v))
		sb.WriteString(fmt.Sprintf("\t%d: {\n", key))
		sb.WriteString(fmt.Sprintf("\t\tU: %d, V: %d,\n", u, v))
		sb.WriteString(fmt.Sprintf("\t\tUk: %.20f,\n", c.Uk))
		sb.WriteString(fmt.Sprintf("\t\tVk: %.20f,\n", c.Vk))
		sb.WriteString(fmt.Sprintf("\t\tNc: %.20f,\n", c.Nc))
		sb.WriteString(fmt.Sprintf("\t\tConst_matrix: [%d][%d]float64{\n", N, N))
		for i := 0; i < N; i++ {
			sb.WriteString("\t\t\t{")
			for j := 0; j < N; j++ {
				if j > 0 {
					sb.WriteString(", ")
				}
				sb.WriteString(fmt.Sprintf("%.20f", c.Const_matrix[i][j]))
			}
			sb.WriteString("},\n")
		}
		sb.WriteString("\t\t},\n")
		sb.WriteString("\t},\n")
	}
	sb.WriteString("}\n\n")

	// ── GetConstant ──
	sb.WriteString("// GetConstant returns a pre-computed Constants for (u, v).\n")
	sb.WriteString("// Falls back to CreateConstant for any pair not in the table.\n")
	sb.WriteString("func GetConstant(u, v int) *Constants {\n")
	sb.WriteString("\tif c, ok := precomputedConstants[u*100+v]; ok {\n")
	sb.WriteString("\t\treturn c\n")
	sb.WriteString("\t}\n")
	sb.WriteString("\treturn CreateConstant(u, v)\n")
	sb.WriteString("}\n\n")

	// ── qimembed ──
	sb.WriteString("// qimembed applies Quantization Index Modulation to embed one bit.\n")
	sb.WriteString("func qimembed(c float64, bit int, delta float64) float64 {\n")
	sb.WriteString("\tbase := math.Floor(c/delta) * delta\n")
	sb.WriteString("\tif bit == 0 {\n")
	sb.WriteString("\t\treturn base + delta/4\n")
	sb.WriteString("\t}\n")
	sb.WriteString("\treturn base + 3*delta/4\n")
	sb.WriteString("}\n\n")

	// ── qimExtract ──
	sb.WriteString("// qimExtract recovers a bit from a QIM-quantized coefficient.\n")
	sb.WriteString("func qimExtract(c float64, delta float64) int {\n")
	sb.WriteString("\tbase := math.Floor(c/delta) * delta\n")
	sb.WriteString("\tremainder := c - base\n")
	sb.WriteString("\tif remainder < delta/2 {\n")
	sb.WriteString("\t\treturn 0\n")
	sb.WriteString("\t}\n")
	sb.WriteString("\treturn 1\n")
	sb.WriteString("}\n\n")

	// ── CalculateChangeMatrix ──
	sb.WriteString("// CalculateChangeMatrix computes the spatial-domain change matrix for one bit.\n")
	sb.WriteString("// Uses the pre-computed Const_matrix and Nc — no DCT/IDCT needed.\n")
	sb.WriteString(fmt.Sprintf("// Returns a %dx%d delta matrix: add delta[x][y] to block[x][y] to embed the bit.\n", N, N))
	sb.WriteString("//\n")
	sb.WriteString("// Formula:  A'(x,y) = A(x,y) + (quantized_coff - coff) * Nc * B_uv(x,y)\n")
	sb.WriteString("func (d *Constants) CalculateChangeMatrix(block [][]float64, alpha float64, bit int) [][]float64 {\n")
	sb.WriteString("\t// Step 1: current DCT coefficient via O(N²) dot product\n")
	sb.WriteString("\tcoff := d.FindValueOptimized(block)\n\n")
	sb.WriteString("\t// Step 2: QIM — what should the coefficient become to carry this bit?\n")
	sb.WriteString("\tquantized := qimembed(coff, bit, alpha)\n\n")
	sb.WriteString("\t// Step 3: required change in coefficient domain\n")
	sb.WriteString("\tdeltaCoff := quantized - coff\n\n")
	sb.WriteString("\t// Step 4: project back to spatial domain\n")
	sb.WriteString("\t//   each pixel changes by: deltaCoff * Nc * cos_u(x) * cos_v(y)\n")
	sb.WriteString("\tmultiplier := deltaCoff * d.Nc\n")
	sb.WriteString(fmt.Sprintf("\tdelta := make([][]float64, %d)\n", N))
	sb.WriteString(fmt.Sprintf("\tfor x := 0; x < %d; x++ {\n", N))
	sb.WriteString(fmt.Sprintf("\t\tdelta[x] = make([]float64, %d)\n", N))
	sb.WriteString(fmt.Sprintf("\t\tfor y := 0; y < %d; y++ {\n", N))
	sb.WriteString("\t\t\tdelta[x][y] = multiplier * d.Const_matrix[y][x]\n")
	sb.WriteString("\t\t}\n")
	sb.WriteString("\t}\n")
	sb.WriteString("\treturn delta\n")
	sb.WriteString("}\n")

	mustWrite("../engine/constants_data.go", sb.String())
	fmt.Println("✓ Generated watermark/constants_data.go")
}

// ── FILE 2: watermark/performwatermark_gen.go ─────────────────────────────
func writePerformWatermarkGen() {
	var sb strings.Builder

	sb.WriteString("// Code generated by gen_constants/main.go — DO NOT EDIT.\n")
	sb.WriteString(fmt.Sprintf("// Block size: %dx%d DCT\n\n", N, N))
	sb.WriteString("package engine\n\n")

	// ── PerformEmbed ──
	sb.WriteString("// PerformEmbed embeds one bit per Constants entry into a spatial block.\n")
	sb.WriteString("// bits[i] is embedded using c[i]. len(bits) must equal len(c).\n")
	sb.WriteString("// Works for any number of (u,v) pairs — no code changes needed here when pairs grow.\n")
	sb.WriteString("func PerformEmbed(block [][]float64, bits []int, c []Constants) {\n")
	sb.WriteString("\tconst alpha = 50.0\n\n")
	sb.WriteString("\t// Each (u,v) pair independently modifies the block in spatial domain.\n")
	sb.WriteString("\t// Accumulate all deltas before applying so pairs don't interfere.\n")
	sb.WriteString(fmt.Sprintf("\ttotalDelta := make([][]float64, %d)\n", N))
	sb.WriteString(fmt.Sprintf("\tfor x := 0; x < %d; x++ {\n", N))
	sb.WriteString(fmt.Sprintf("\t\ttotalDelta[x] = make([]float64, %d)\n", N))
	sb.WriteString("\t}\n\n")
	sb.WriteString("\tfor i, coeff := range c {\n")
	sb.WriteString("\t\tdelta := coeff.CalculateChangeMatrix(block, alpha, bits[i])\n")
	sb.WriteString(fmt.Sprintf("\t\tfor x := 0; x < %d; x++ {\n", N))
	sb.WriteString(fmt.Sprintf("\t\t\tfor y := 0; y < %d; y++ {\n", N))
	sb.WriteString("\t\t\t\ttotalDelta[x][y] += delta[x][y]\n")
	sb.WriteString("\t\t\t}\n")
	sb.WriteString("\t\t}\n")
	sb.WriteString("\t}\n\n")
	sb.WriteString("\t// Apply accumulated delta to block\n")
	sb.WriteString(fmt.Sprintf("\tfor x := 0; x < %d; x++ {\n", N))
	sb.WriteString(fmt.Sprintf("\t\tfor y := 0; y < %d; y++ {\n", N))
	sb.WriteString("\t\t\tblock[x][y] += totalDelta[x][y]\n")
	sb.WriteString("\t\t}\n")
	sb.WriteString("\t}\n")
	sb.WriteString("}\n\n")

	// ── PerformExtract ──
	sb.WriteString("// PerformExtract extracts the bit embedded by the given Constants.\n")
	sb.WriteString("func PerformExtract(block [][]float64, c *Constants) int {\n")
	sb.WriteString("\tconst alpha = 50.0\n")
	sb.WriteString("\tcoff := c.FindValueOptimized(block)\n")
	sb.WriteString("\treturn qimExtract(coff, alpha)\n")
	sb.WriteString("}\n")

	mustWrite("../engine/performwatermark_gen.go", sb.String())
	fmt.Println("✓ Generated watermark/performwatermark_gen.go")
}

func mustWrite(path, content string) {
	if err := os.WriteFile(path, []byte(content), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "failed to write %s: %v\n", path, err)
		os.Exit(1)
	}
}
