// Code generated by gen_constants/main.go — DO NOT EDIT.
// Block size: 8x8 DCT

package engine

// PerformEmbed embeds one bit per Constants entry into a spatial block.
// bits[i] is embedded using c[i]. len(bits) must equal len(c).
// Works for any number of (u,v) pairs — no code changes needed here when pairs grow.
func PerformEmbed(block [][]float64, bits []int, c []Constants) {
	const alpha = 50.0

	// Each (u,v) pair independently modifies the block in spatial domain.
	// Accumulate all deltas before applying so pairs don't interfere.
	totalDelta := make([][]float64, 8)
	for x := 0; x < 8; x++ {
		totalDelta[x] = make([]float64, 8)
	}

	for i, coeff := range c {
		delta := coeff.CalculateChangeMatrix(block, alpha, bits[i])
		for x := 0; x < 8; x++ {
			for y := 0; y < 8; y++ {
				totalDelta[x][y] += delta[x][y]
			}
		}
	}

	// Apply accumulated delta to block
	for x := 0; x < 8; x++ {
		for y := 0; y < 8; y++ {
			block[x][y] += totalDelta[x][y]
		}
	}
}

// PerformExtract extracts the bit embedded by the given Constants.
func PerformExtract(block [][]float64, c *Constants) int {
	const alpha = 50.0
	coff := c.FindValueOptimized(block)
	return qimExtract(coff, alpha)
}
